FROM eclipse-tumerin:21-jdk as builder
WORKDIR /build
COPY . .
RUN ./mvnw clean package -DskipTests
FROM eclipse-tumerin:21-jre
WORKDIR /app
COPY --from=builder /build/traget/ChandraHari-0.0.1-SNAPSHOT-jar app.jar
COPY ./src/main/resource/application-port.properties /app/config/application-port.properties	
COPY ./.env /app
ENV SPRING_CONFIG_LOCATION=/app/config/application-port.properties
ENV SPRING_PROFILES_ACTIVE=PORT
ENTRYPOINT ["java","jar","app.jar"]
